### ISSUE TITLE
add repository link to dockerhub auto build to get automatic rebuilds when debian updates

### ISSUE THREAD

**Issue by tfoote** [mikepurvis/aptly-docker#6]
There have not been many changes here, but debian has released security updates etc. If you configure the dockerhub automatic builds to be dependent on the debian docker repository this will automatically be rebuild anytime the dependencies (debian) changes.

https://docs.docker.com/docker-hub/builds/#repository-links

**Comment by mikepurvis** [comment]
Having all of Debian for this is probably overkill— `aptly` is a standalone Go binary, so the deb could really just be unpacked on top of a minimal Alpine base or something.

**Comment by mikepurvis** [comment]
But I think I've set up the link to debian now, so it should rebuild as required.

**Comment by tfoote** [comment]
Yeah, there's definitely space to optimize, but this is fine for now. Thanks.
